# DonutCore Configuration
# by Donut4GAMER
# thanks for downloading the plugin <3

# here you can configure the gamemode command form DonutCore
gamemode:
  # configure the permissions for the /gm, /gmc, ... commands
  permissions:
    # the permission users need to use the gamemode commands
    gamemode-self: "donutcore.gamemode.self"
    # the permission users need to set other players gamemode
    gamemode-others: "donutcore.gamemode.others"

  # configure the messages for the /gm, /gmc, ... commands
  # use the placeholders %gamemode%, %target% and %player%
  messages:
    # message that appears when you execute the command as the console
    no-player: "&6DonutCore &8| &cOnly players can execute this."
    # message that appears when you do not have the permission you have set above
    no-permission: "&6DonutCore &8| &cYou do not have the permission to do that."
    # message that appears when you just type /gm, for example
    usage: "&6DonutCore &8| &cUsage: /gm <0/1/2/3|s/c/a/sp> [Player]"
    # message that appears when you do not write a valid gamemode
    invalid-gamemode: "&6DonutCore &8| &cThis gamemode does not exist."
    # message that appears when you type a username from an offline/not existing user
    player-not-found: "&6DonutCore &8| &cPlayer not found."
    # message that appears when you have changed your gamemode
    self-change: "&6DonutCore &8| &7Your gamemode has been changed to &6%gamemode%&7."
    # message that appears when you have set another users gamemode
    other-change-sender: "&6DonutCore &8| &7You have set &6%target%&7's gamemode to &6%gamemode%&7."
    # message that appears when someone set your gamemode
    other-change-target: "&6DonutCore &8| &7Your gamemode was set to &6%gamemode%&7 by &6%player%&7."

# here you can configure the chat feature from DonutCore
chat:
  # configure the text you can type that will be replaced with an emoji or something else
  replacements:
    "[o/]": "§e§lヾ(＾∇＾)"
    "[yay]": "§b§l(╯°□°)╯"
    "[lol]": "§d§l(≧▽≦)"
    "[what]": "§c§l(⊙_☉)"
    "[omg]": "§6§lΣ(°ロ°)"
    "[rip]": "§8§l(✖╭╮✖)"
    "[shrug]": "§7¯\\_(ツ)_/¯"
    "[rage]": "§4§l(ノಠ益ಠ)ノ彡┻━┻"
    "bad word": "good word"

# here you can configure the tablist feature from DonutCore
tablist:
  # do you want to enable the DonutCore Tablist?
  enabled: true
  # after how many ticks should the Tablist update? (100 Ticks=5 Seconds)
  update-interval: 100
  # set the Header and Footer of the Tablist
  # PlaceholderAPI support
  header:
    - "&r"
    - "&7Welcome on our Server"
    - "&7User: &6%player_name%"
    - "&r"
  footer:
    - "&r"
    - "&7Thanks for Downloading"
    - "&7Discord: &6https://discord.gg/Yarpy8tAqJ"
    - "&r"

# here you can configure the scoreboard feature from DonutCore
scoreboard:
  # do you want to enable the DonutCore Scoreboard?
  enabled: true
  # after how many ticks should the Tablist update? (100 Ticks=5 Seconds)
  update-interval: 100
  # set the title of the Scoreboard
  title: "&6&lDonut&f&lCore"
  # set the Scoreboard lines (every line needs to be unique!!!)
  # PlaceholderAPI support
  lines:
    - "&r&8----------------"
    - "&7Name: &6%player_name%"
    - "&7Ping: &6%player_ping%"
    - "&r"
    - "&7Discord:"
    - "&6https://discord.gg/Yarpy8tAqJ"
    - "&8----------------"

# here you can configure the ip command from DonutCore
ip:
  # configure the permissions for the /ip command
  permissions:
    # the permission users need to execute his command
    view: "donutcore.ip.view"

  # configure the messages for the /ip command
  # use the placeholders %target% and %ip%
  messages:
    # message that appears when you execute the command as the console
    no-player: "&6DonutCore &8| &cOnly players can execute this."
    # message that appears when you do not have the permission you have set above
    no-permission: "&6DonutCore &8| &cYou do not have the permission to do that."
    # message that appears when you just type /ip, for example
    usage: "&6DonutCore &8| &cUsage: /ip <player>"
    # message that apears when you have executed the command and the player is offline
    player-not-found: "&6DonutCore &8| &7The Player &6%target% &7is not online!"
    # message that apears when you have executed the command and the player is online
    show-ip: "&6DonutCore &8| &7The IP from &6%target% &7is: &6%ip%"